// src/pages/system/menu/index.tsx
import type { FormData } from '#/form';
import type { PagePermission, TableOptions } from '#/public';
import type { FormFn } from '@/components/Form/BasicForm';
import { useCallback, useEffect, useRef, useState } from 'react';
import { searchList, createList, tableColumns } from './model';
import { message } from 'antd';
import { useTranslation } from 'react-i18next';
import { checkPermission } from '@/utils/permissions';
import { useCommonStore } from '@/hooks/useCommonStore';
import { ADD_TITLE, EDIT_TITLE } from '@/utils/config';
import { BasicBtn, UpdateBtn, DeleteBtn } from '@/components/Buttons';
import {
  getMenuList,
  getMenuById,
  createMenu,
  updateMenu,
  deleteMenu
} from '@/servers/system/menu';
import BasicContent from '@/components/Content/BasicContent';
import BasicSearch from '@/components/Search/BasicSearch';
import BasicModal from '@/components/Modal/BasicModal';
import BasicForm from '@/components/Form/BasicForm';
import BasicTable from '@/components/Table/BasicTable';

// 当前行数据
interface RowData {
  id: string;
}

// 初始化搜索数据
const initSearch = {
};

// 初始化新增数据
const initCreate = {
  sortNum: 1,
};

function Page() {
  const { t } = useTranslation();
  const searchFormRef = useRef<FormFn>(null);
  const createFormRef = useRef<FormFn>(null);
  const [isCreateOpen, setCreateOpen] = useState(false);
  const [isLoading, setLoading] = useState(false);
  const [isCreateLoading, setCreateLoading] = useState(false);
  const [createTitle, setCreateTitle] = useState(ADD_TITLE(t));
  const [createId, setCreateId] = useState('');
  const [createData, setCreateData] = useState<FormData>(initCreate);
  const [tableData, setTableData] = useState<FormData[]>([]);
  const [messageApi, contextHolder] = message.useMessage();
  const { permissions } = useCommonStore();

  // 权限前缀
  const permissionPrefix = '/system/menu';

  // 权限
  const pagePermission: PagePermission = {
    page: checkPermission(`${permissionPrefix}/search`, permissions),
    create: checkPermission(`${permissionPrefix}/create`, permissions),
    update: checkPermission(`${permissionPrefix}/update`, permissions),
    delete: checkPermission(`${permissionPrefix}/delete`, permissions)
  };

  /**
   * 点击搜索
   * @param values - 表单返回数据
   */
  const onSearch = (values: FormData) => {
    handleSearch(values);
  };

  /**
   * 处理搜索
   * @param values - 表单返回数据
   */
  const handleSearch = useCallback(async (values: FormData) => {
    try {
      setLoading(true);
      const res = await getMenuList({...values, isAll: true});
      const { code, data } = res;
      if (Number(code) !== 200) return;
      setTableData(data as unknown as FormData[]);
    } finally {
      setLoading(false);
    }
  }, []);

  // 首次进入自动加载接口数据
  useEffect(() => { 
    if (pagePermission.page) handleSearch({ ...initSearch });
  }, [handleSearch, pagePermission.page]);

  /**
   * 点击新增
   * @param id
   */
  const onCreate = (id?: string) => {
    setCreateOpen(true);
    setCreateTitle(ADD_TITLE(t));
    setCreateId('');
    setCreateData({ ...initCreate, parentId: id });
  };

  /**
   * 点击编辑
   * @param id - 唯一值
   */
  const onUpdate = async (id: string) => {
    try {
      setCreateOpen(true);
      setCreateTitle(EDIT_TITLE(t, id));
      setCreateId(id);
      setCreateLoading(true);
      const { code, data } = await getMenuById(id as string);
      if (Number(code) !== 200) return;
      setCreateData(data);
    } finally {
      setCreateLoading(false);
    }
  };

  /** 表单提交 */
  const createSubmit = () => {
    createFormRef.current?.handleSubmit();
  };

  /** 关闭新增/修改弹窗 */
  const closeCreate = () => {
    setCreateOpen(false);
  };

  /** 获取表格数据 */
  const getPage = () => {
    const formData = searchFormRef.current?.getFieldsValue() || {};
    const params = { ...formData };
    handleSearch(params);
  };

  /**
   * 新增/编辑提交
   * @param values - 表单返回数据
   */
  const handleCreate = async (values: FormData) => {
    try {
      setCreateLoading(true);
      const functions = () => createId ? updateMenu(createId, values) : createMenu(values);
      const { code, message } = await functions();
      if (Number(code) !== 200) return;
      messageApi.success(message || t('public.successfulOperation'));
      setCreateOpen(false);
      getPage();
    } finally {
      setCreateLoading(false);
    }
  };

  /**
   * 点击删除
   * @param id - 唯一值
   */
  const onDelete = async (id: string) => {
    try {
      setLoading(true);
      const { code, message } = await deleteMenu(id as string);
      if (Number(code) === 200) {
        messageApi.success(message || t('public.successfullyDeleted'));
        getPage();
      }
    } finally {
      setLoading(false);
    }
  };

  /**
   * 渲染操作
   * @param _ - 当前值
   * @param record - 当前行参数
   */
  const optionRender: TableOptions<object> = (_, record) => (
    <>
      {
        pagePermission.create === true &&
        <BasicBtn
          className='mr-5px'
          isLoading={isLoading}
          onClick={() => onCreate((record as RowData).id)}
        >
          { t('system.addTreeChildren') }
        </BasicBtn>
      }
      {
        pagePermission.update === true &&
        <UpdateBtn
          className='mr-5px'
          isLoading={isLoading}
          onClick={() => onUpdate((record as RowData).id)}
        />
      }
      {
        pagePermission.delete === true &&
        <DeleteBtn
          className='mr-5px'
          isLoading={isLoading}
          handleDelete={() => onDelete((record as RowData).id)}
        />
      }
    </>
  );

  return (
    <BasicContent isPermission={pagePermission.page}>
      <>
        { contextHolder }
        <BasicSearch
          formRef={searchFormRef}
          list={searchList(t)}
          data={initSearch}
          isLoading={isLoading}
          isCreate={pagePermission.create}
          onCreate={onCreate}
          handleFinish={onSearch}
        />
        
        <BasicTable
          loading={isLoading}
          columns={tableColumns(t, optionRender)}
          dataSource={tableData}
        />

        <BasicModal
          width={1200}
          title={createTitle}
          open={isCreateOpen}
          confirmLoading={isCreateLoading}
          onOk={createSubmit}
          onCancel={closeCreate}
        >
          <BasicForm
            formRef={createFormRef}
            layout='inline'
            list={createList(t)}
            data={createData}
            labelCol={{ span: 4 }}
            wrapperCol={{ span: 19 }}
            handleFinish={handleCreate}
          />
        </BasicModal>
      </>
    </BasicContent>
  );
}

export default Page;

// src/pages/systems/menu/index.vue
<template>
  <BasicContent :isPermission="checkPermission(pagePermission.page)">
    <template #top>
      <BasicSearch
        :list="searchList"
        :data="searchData"
        :isLoading="isLoading"
        @handleFinish="handleSearch"
      />
    </template>

    <BtnRow>
      <CreateBtn
        v-if="checkPermission(pagePermission.create)"
        @click="onCreate"
      />
    </BtnRow>

    <BasicTable
      :data="tableData"
      :columns="tableColumns"
      :isLoading="isLoading"
    >
      <template #icon="{ record }">
        <Icon
          v-if="record?.icon"
          :icon="record?.icon"
          class="text-20px"
        />
        <span v-else>
          {{ EMPTY_VALUE }}
        </span>
      </template>

      <template #operate='{ record }'>
        <UpdateBtn
          v-if="checkPermission(pagePermission.update)"
          class="btn-space"
          :isLoading="isCreateLoading"
          @click="onUpdate(record)"
        />
        <DeleteBtn
          v-if="checkPermission(pagePermission.delete)"
          class="btn-space"
          :isLoading="isLoading"
          @click="handleDelete(record.id)"
        />
        <BasicBtn
          v-if="checkPermission(pagePermission.create)"
          :isLoading="isLoading"
          @click="onCreate(record.id)"
        >
          添加下级菜单
        </BasicBtn>
      </template>
    </BasicTable>
  </BasicContent>

  <BasicModal
    v-model:isOpen="creates.isOpen"
    :isLoading="isCreateLoading"
    :title="creates.title"
    @handleFinish="createSubmit"
    @handleCancel="onCloseCreate"
  >
    <BasicForm
      ref="createFormRef"
      :list="createList(handleFilterParent(tableData), creates.data?.type as number)"
      :labelCol="{ span: 6 }"
      :data="creates.data"
      @handleFinish="handleCreate"
    />
  </BasicModal>
</template>

<script lang="ts" setup>
import type { FormData } from '#/form';
import type { BasicFormProps } from '@/components/Form/model';
import type { CreateData, TableData } from '#/public';
import { message } from 'ant-design-vue';
import { onActivated, reactive, shallowRef, ref } from 'vue';
import { UpdateBtn, DeleteBtn, BasicBtn, CreateBtn } from '@/components/Buttons';
import { ADD_TITLE, EDIT_TITLE, EMPTY_VALUE } from '@/utils/config';
import { checkPermission } from "@/utils/permissions";
import { Icon } from '@iconify/vue';
import {
  searchList,
  createList,
  tableColumns,
  pagePermission
} from './model';
import {
  getSystemMenuTree,
  getSystemMenuById,
  createSystemMenu,
  updateSystemMenu,
  deleteSystemMenu
} from '@/servers/systems/menu';
import BtnRow from '@/components/BtnRow/index.vue';
import BasicContent from '@/components/Content/BasicContent.vue';
import BasicTable from '@/components/Table/BasicTable.vue';
import BasicSearch from '@/components/Search/BasicSearch.vue';
import BasicForm from '@/components/Form/BasicForm.vue';
import BasicModal from '@/components/Modal/BasicModal.vue';

defineOptions({
  name: 'SystemsMenu'
});

const isLoading = ref(false);
const isCreateLoading = ref(false);
const createFormRef = shallowRef<BasicFormProps>();

// 初始化新增数据
const initCreate = {
  sortNum: 1,
  parentId: '0'
};

// 搜索数据
const searchData = ref<FormData>({});

// 新增数据
const creates = reactive<CreateData>({
  id: '',
  isOpen: false,
  title: ADD_TITLE,
  data: {...initCreate},
  type: 'create'
});

// 表格数据
const tableData = ref<TableData[]>([]);

onActivated(() => {
  getPage();
});

/** 获取表格数据 */
const getPage = async () => {
  const query = { ...searchData.value };
  try {
    isLoading.value = true;
    const { code, data } = await getSystemMenuTree(query);
    if (Number(code) !== 200) return;
    tableData.value = JSON.parse(JSON.stringify(data));
  } finally {
    isLoading.value = false;
  }
};

/** 表格提交 */
const createSubmit = () => {
  createFormRef.value?.handleSubmit();
};

/**
 * 父级菜单处理
 * @param list - 表格列表
 */
const handleFilterParent = (list: TableData[]): TableData[] => {
  const result: TableData[] = [
    {
      name: '顶级菜单',
      id: '0',
      children: list
    }
  ];

  return result;
};

/**
 * 搜索提交
 * @param values - 表单返回数据
 */
const handleSearch = (values: FormData) => {
  searchData.value = values;
  getPage();
};

/** 点击新增 */
const onCreate = (id?: string) => {
  creates.isOpen = !creates.isOpen;
  creates.title = ADD_TITLE;
  creates.id = id || '';
  creates.type = 'create';
  const params = {...initCreate};
  params.parentId = id || params.parentId || '';
  creates.data = params;
};

/**
 * 点击编辑
 * @param record - 当前行数据
 */
const onUpdate = async (record: FormData) => {
  const { id, name } = record;
  creates.isOpen = !creates.isOpen;
  creates.id = id as string;
  creates.title = EDIT_TITLE(name as string);
  creates.type = 'update';

  try {
    isCreateLoading.value = true;
    const { code, data } = await getSystemMenuById(id as string);
    if (Number(code) !== 200) return;
    creates.data = (data || {}) as FormData;
  } finally {
    isCreateLoading.value = false;
  }
};

/**
 * 新增/编辑提交
 * @param values - 表单返回数据
 */
const handleCreate = async () => {
  try {
    isCreateLoading.value = true;
    const functions = creates.type === 'update' ? updateSystemMenu(creates.id, creates.data) : createSystemMenu(creates.data);
    const { code } = await functions;
    if (Number(code) !== 200) return;
    getPage();
    creates.id = '';
    creates.isOpen = false;
    creates.data = {...initCreate};
    createFormRef.value?.handleReset();
    message.success('操作成功');
  } finally {
    isCreateLoading.value = false;
  }
};

/** 关闭新增/编辑 */
const onCloseCreate = () => {
  creates.isOpen = false;
};

/**
 * 删除
 * @param id - 唯一标识
 */
const handleDelete = async (id: string | number) => {
  try {
    isLoading.value = true;
    const { code } = await deleteSystemMenu(id as string);
    if (Number(code) === 200) {
      message.success('删除成功');
      getPage();
    }
  } finally {
    isLoading.value = false;
  }
};
</script>
