// src/pages/operations/article/index.vue
<template>
  <BasicContent :isPermission="checkPermission(pagePermission.page)">
    <template #top>
      <BasicSearch
        :list="searchList"
        :data="searchData"
        :isLoading="isLoading"
        @handleFinish="handleSearch"
      />
    </template>

    <BtnRow>
      <CreateBtn
        v-if="checkPermission(pagePermission.create)"
        @click="onCreate"
      />
    </BtnRow>

    <BasicTable
      :data="tableData"
      :columns="tableColumns"
      :isLoading="isLoading"
      :pagination="{
        current: pagination.page,
        pageSize: pagination.pageSize,
        total: pagination.total,
        onChange: handlePagination,
      }"
    >
      <template #operate="{ record }">
        <UpdateBtn
          v-if="checkPermission(pagePermission.update)"
          class="btn-space"
          :isLoading="isCreateLoading"
          @click="onUpdate(record)"
        />
        <DeleteBtn
          v-if="checkPermission(pagePermission.delete)"
          :isLoading="isLoading"
          @click="handleDelete(record.id)"
        />
      </template>
    </BasicTable>
  </BasicContent>
</template>

<script lang="ts" setup>
import type { FormData } from '#/form';
import type { TableData, PaginationData } from '#/public';
import { useRouter } from 'vue-router';
import { message } from 'ant-design-vue';
import { onActivated, reactive, ref } from 'vue';
import { UpdateBtn, DeleteBtn, CreateBtn } from '@/components/Buttons';
import { pagePermission, searchList, tableColumns } from './model';
import { checkPermission } from '@/utils/permissions';
import { usePublicStore } from '@/stores/public';
import { PAGE_SIZE } from '@/utils/config';
import { storeToRefs } from 'pinia';
import { getArticlePage, deleteArticle } from '@/servers/operations/article';
import BtnRow from '@/components/BtnRow/index.vue';
import BasicContent from '@/components/Content/BasicContent.vue';
import BasicTable from '@/components/Table/BasicTable.vue';
import BasicSearch from '@/components/Search/BasicSearch.vue';

defineOptions({
  name: 'OperationsArticle'
});

const router = useRouter();
const publicStore = usePublicStore();
const { setRefreshPage } = publicStore;
const { isRefreshPage } = storeToRefs(publicStore);
const isLoading = ref(false);
const isCreateLoading = ref(false);

// 搜索数据
const searchData = ref<FormData>({});

// 表格数据
const tableData = ref<TableData[]>([]);

// 分页数据
const pagination = reactive<PaginationData>({
  total: 0,
  page: 1,
  pageSize: PAGE_SIZE,
});

onActivated(() => {
  if (!isRefreshPage.value) {
    getPage();
  }
});

onActivated(() => {
  if (isRefreshPage.value) {
    getPage();
    setRefreshPage(false);
  }
});

/** 获取表格数据 */
const getPage = async () => {
  const newPagination = { ...pagination };
  delete newPagination.total;
  const query = { ...newPagination, ...searchData.value };
  try {
    isLoading.value = true;
    const { code, data } = await getArticlePage(query);
    if (Number(code) !== 200) return;
    const { items, total } = data;
    tableData.value = items;
    pagination.total = Number(total) || 0;
  } finally {
    isLoading.value = false;
  }
};

/**
  * 搜索提交
  * @param values - 表单返回数据
  */
const handleSearch = (values: FormData) => {
  searchData.value = values;
  pagination.page = 1;
  getPage();
};

/** 点击新增 */
const onCreate = () => {
  router.push('/content/article/option?type=create');
};

/**
  * 点击编辑
  * @param record - 当前行数据
  */
const onUpdate = async (record: FormData) => {
  const { id } = record;
  router.push(`/content/article/option?type=update&id=${id as string}`);
};

/**
  * 删除
  * @param id - 唯一标识
  */
const handleDelete = async (id: string | number) => {
  try {
    isLoading.value = true;
    const data = await deleteArticle(id as string);
    if (data?.code === 200) {
      message.success(data?.message || '删除成功');
      getPage();
    }
  } finally {
    isLoading.value = false;
  }
};

/**
  * 分页
  * @param page - 当前页
  * @param pageSize - 分页总数
  */
const handlePagination = (page: number, pageSize: number) => {
  pagination.page = page;
  pagination.pageSize = pageSize;
  getPage();
};
</script>
@/servers/operations/article

// src/pages/content/article/index.tsx
import type { FormData } from '#/form';
import type { PagePermission, TableOptions } from '#/public';
import { useCallback, useEffect, useState } from 'react';
import { searchList, tableColumns } from './model';
import { message } from 'antd';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { checkPermission } from '@/utils/permissions';
import { useCommonStore } from '@/hooks/useCommonStore';
import { UpdateBtn, DeleteBtn } from '@/components/Buttons';
import { getArticlePage, deleteArticle } from '@/servers/content/article';
import { INIT_PAGINATION } from '@/utils/config';
import BasicContent from '@/components/Content/BasicContent';
import BasicSearch from '@/components/Search/BasicSearch';
import BasicTable from '@/components/Table/BasicTable';
import BasicPagination from '@/components/Pagination/BasicPagination';
import BasicCard from '@/components/Card/BasicCard';
import { usePublicStore } from '@/stores';

// 当前行数据
interface RowData {
  id: string;
}

function Page() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { permissions } = useCommonStore();
  const [isFetch, setFetch] = useState(false);
  const [isLoading, setLoading] = useState(false);
  const [searchData, setSearchData] = useState<FormData>({});
  const [page, setPage] = useState(INIT_PAGINATION.page);
  const [pageSize, setPageSize] = useState(INIT_PAGINATION.pageSize);
  const [total, setTotal] = useState(0);
  const [tableData, setTableData] = useState<FormData[]>([]);
  const [messageApi, contextHolder] = message.useMessage();
  const setRefreshPage = usePublicStore(state => state.setRefreshPage);
  const isRefreshPage = usePublicStore(state => state.isRefreshPage);

  // 权限前缀
  const permissionPrefix = '/content/article';

  // 权限
  const pagePermission: PagePermission = {
    page: checkPermission(`${permissionPrefix}/index`, permissions),
    create: checkPermission(`${permissionPrefix}/create`, permissions),
    update: checkPermission(`${permissionPrefix}/update`, permissions),
    delete: checkPermission(`${permissionPrefix}/delete`, permissions)
  };

  /** 获取表格数据 */
  const getPage = useCallback(async () => {
    const params = { ...searchData, page, pageSize };

    try {
      setLoading(true);
      const { code, data } = await getArticlePage(params);

      if (Number(code) === 200) {
        const { items, total } = data;
        setTotal(total);
        setTableData(items);
      }
    } finally {
      setFetch(false);
      setLoading(false);
    }
  }, [page, pageSize, searchData]);

  useEffect(() => {
    if (isFetch) getPage();
  }, [getPage, isFetch]);

  /**
   * 点击搜索
   * @param values - 表单返回数据
   */
  const onSearch = (values: FormData) => {
    setPage(1);
    setSearchData(values);
    setFetch(true);
  };

  // 首次进入自动加载接口数据
  useEffect(() => {
    if (pagePermission.page && !isRefreshPage) getPage();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pagePermission.page]);

  // 如果是新增或编辑成功重新加载页面
  useEffect(() => {
    if (isRefreshPage) {
     setRefreshPage(false);
      getPage();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isRefreshPage]);

  /** 点击新增 */
  const onCreate = () => {
    navigate('/content/article/option?type=create');
  };

  /**
   * 点击编辑
   * @param id - 唯一值
   */
  const onUpdate = (id: string) => {
    navigate(`/content/article/option?type=update&id=${id}`);
  };

  /**
   * 点击删除
   * @param id - 唯一值
   */
  const onDelete = async (id: string) => {
    try {
      setLoading(true);
      const { code, message } = await deleteArticle(id as string);
      if (Number(code) === 200) {
        messageApi.success(message || t('public.successfullyDeleted'));
        getPage();
      }
    } finally {
      setLoading(false);
    }
  };

  /**
   * 处理分页
   * @param page - 当前页数
   * @param pageSize - 每页条数
   */
  const onChangePagination = (page: number, pageSize: number) => {
    setPage(page);
    setPageSize(pageSize);
    setFetch(true);
  };

  /**
   * 渲染操作
   * @param _ - 当前值
   * @param record - 当前行参数
   */
  const optionRender: TableOptions<object> = (_, record) => (
    <>
      {
        pagePermission.update === true &&
        <UpdateBtn
          className='mr-5px'
          isLoading={isLoading}
          onClick={() => onUpdate((record as RowData).id)}
        />
      }
      {
        pagePermission.delete === true &&
        <DeleteBtn
          className='mr-5px'
          isLoading={isLoading}
          handleDelete={() => onDelete((record as RowData).id)}
        />
      }
    </>
  );

  return (
    <BasicContent isPermission={pagePermission.page}>
      { contextHolder }
      <BasicCard>
        <BasicSearch
          list={searchList(t)}
          data={searchData}
          isLoading={isLoading}
          handleFinish={onSearch}
        />
      </BasicCard>

      <BasicCard className='mt-10px'>
        <BasicTable
          isLoading={isLoading}
          isCreate={pagePermission.create}
          columns={tableColumns(t, optionRender)}
          dataSource={tableData}
          getPage={getPage}
          onCreate={onCreate}
        />

        <BasicPagination
          disabled={isLoading}
          current={page}
          pageSize={pageSize}
          total={total}
          onChange={onChangePagination}
        />
      </BasicCard>
    </BasicContent>
  );
}

export default Page;
