// src/pages/operations/article/option.vue
<template>
  <BasicContent :isPermission="isPermission">
    <Spin class='mb-50px' :spinning="isLoading">
      <BasicForm
        ref="createFormRef"
        :list="createList"
        :labelCol="{ span: 5 }"
        :data="createData"
        @handleFinish="handleFinish"
      />
    </Spin>

    <SubmitBottom
      :isLoading="isLoading"
      @submit="handleSubmit"
    />
  </BasicContent>
</template>

<script lang="ts" setup>
import type { FormData } from '#/form';
import type { BasicFormProps } from '@/components/Form/model';
import { onMounted, watch, shallowRef, ref } from 'vue';
import { checkPermission } from '@/utils/permissions';
import { useRoute, useRouter } from 'vue-router';
import { fatherPath, createList, pagePermission } from './model';
import { useTabStore } from '@/stores/tabs';
import { usePublicStore } from '@/stores/public';
import { message, Spin } from 'ant-design-vue';
import { useSingleTab } from '@/hooks/useSingleTab';
import {
 getArticleById,
 createArticle,
 updateArticle
} from '@/servers/content/article';
import BasicForm from '@/components/Form/BasicForm.vue';
import BasicContent from '@/components/Content/BasicContent.vue';
import SubmitBottom from '@/components/Bottom/SubmitBottom.vue';

defineOptions({
  name: 'ContentArticleOption'
});

// 初始化新增数据
const initCreate = {
  content: '<h4>初始化内容</h4>',
  user: {
    name: {
      test: ''
    }
  }
};

const route = useRoute();
const router = useRouter();
const tabStore = useTabStore();
const { setRefreshPage } = usePublicStore();
const { closeTabGoNext } = tabStore;
const createFormRef = shallowRef<BasicFormProps>();
const isLoading = ref(false);
const createData = ref<FormData>(initCreate);

const id = route.query?.id as string || '';
const isPermission = ref(checkPermission(id ? pagePermission.update : pagePermission.create));
useSingleTab(fatherPath);

onMounted(() => {
  id ? handleUpdate(id) : handleCreate();
});

watch(() => route.query?.id, () => {
  const id = (route.query?.id || '') as string;
  id ? handleUpdate(id) : handleCreate();
  isPermission.value = checkPermission(id ? pagePermission.update : pagePermission.create);
});

/** 处理新增 */
const handleCreate = () => {
  createData.value = initCreate;
};

/**
 * 处理编辑
 * @param id - 唯一值
 */
 const handleUpdate = async (id: string) => {
  try {
    isLoading.value = true;
    const { code, data } = await getArticleById(id);
    if (Number(code) !== 200) return;
    createData.value = (data || {}) as FormData;
  } finally {
    isLoading.value = false;
  }
};

/** 表格提交 */
const handleSubmit = () => {
  createFormRef.value?.handleSubmit();
};

/** 返回主页 */
const goBack = (isRefresh?: boolean) => {
  if (isRefresh) setRefreshPage(true);
  router.push(fatherPath);
  closeTabGoNext(route.path, fatherPath);
};

/**
 * 新增/编辑提交
 * @param values - 表单返回数据
 */
const handleFinish = async (values: FormData) => {
  try {
    isLoading.value = true;
    const functions = () => id ? updateArticle(id, values) : createArticle(values);
    const { code, message: resultMessage } = await functions();
    if (Number(code) !== 200) return;
    message.success(resultMessage || '操作成功');
    createFormRef.value?.handleReset();
    createData.value = initCreate;
    goBack(true);
  } finally {
    isLoading.value = false;
  }
};
</script>@/servers/operations/article

// src/pages/content/article/option.tsx
import type { FormData } from '#/form';
import type { PagePermission } from '#/public';
import { type FormInstance, message, Spin } from 'antd';
import { createList } from './model';
import { getUrlParam } from '@/utils/helper';
import { useLocation } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { checkPermission } from '@/utils/permissions';
import { useCommonStore } from '@/hooks/useCommonStore';
import {
  useEffect,
  useRef,
  useState
} from 'react';
import {
  getArticleById,
  createArticle,
  updateArticle,
} from '@/servers/content/article';
import BasicForm from '@/components/Form/BasicForm';
import BasicContent from '@/components/Content/BasicContent';
import SubmitBottom from '@/components/Bottom/SubmitBottom';
import { useSingleTab } from '@/hooks/useSingleTab';
import BasicCard from '@/components/Card/BasicCard';
import { usePublicStore, useTabsStore } from '@/stores';

interface RecordType {
  key: string;
  title: string;
  description: string;
}

const mockData: RecordType[] = Array.from({ length: 20 }).map((_, i) => ({
  key: i.toString(),
  title: `content${i + 1}`,
  description: `description of content${i + 1}`,
}));

const initialTargetKeys = mockData.filter((item) => Number(item.key) > 10).map((item) => item.key);

// 初始化新增数据
const initCreate = {
  content: '<h4>初始化内容</h4>',
  transfer: initialTargetKeys
};

// 父路径
const fatherPath = '/content/article';

function Page() {
  const { t } = useTranslation();
  const { pathname, search } = useLocation();
  const uri = pathname + search;
  const id = getUrlParam(search, 'id');
  const createFormRef = useRef<FormInstance>(null);
  const [isLoading, setLoading] = useState(false);
  const [createId, setCreateId] = useState('');
  const [createData, setCreateData] = useState<FormData>(initCreate);
  const [messageApi, contextHolder] = message.useMessage();
  const { permissions } = useCommonStore();
  const closeTabGoNext = useTabsStore(state => state.closeTabGoNext);
  const setRefreshPage = usePublicStore(state => state.setRefreshPage);
  useSingleTab(fatherPath);

  // 权限前缀
  const permissionPrefix = '/content/article';

  // 权限
  const pagePermission: PagePermission = {
    create: checkPermission(`${permissionPrefix}/create`, permissions),
    update: checkPermission(`${permissionPrefix}/update`, permissions),
  };

  useEffect(() => {
    id ? handleUpdate(id) : handleCreate();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  /** 处理新增 */
  const handleCreate = () => {
    setCreateId('');
    setCreateData(initCreate);
  };

  /**
   * 处理编辑
   * @param id - 唯一值
   */
   const handleUpdate = async (id: string) => {
    try {
      setCreateId(id);
      setLoading(true);
      const { code, data } = await getArticleById(id as string);
      if (Number(code) !== 200) return;
      setCreateData(data);
    } finally {
      setLoading(false);
    }
  };

  /** 表格提交 */
  const handleSubmit = () => {
    createFormRef.current?.submit();
  };

  /**
   * 返回主页
   * @param isRefresh - 返回页面是否重新加载接口
   */
  const goBack = (isRefresh?: boolean) => {
    createFormRef.current?.resetFields();
    if (isRefresh) setRefreshPage(true);
    closeTabGoNext({
      key: uri,
      nextPath: fatherPath
    });
  };

  /**
   * 新增/编辑提交
   * @param values - 表单返回数据
   */
  const handleFinish = async (values: FormData) => {
    try {
      setLoading(true);
      const functions = () => createId ? updateArticle(createId, values) : createArticle(values);
      const { code, message } = await functions();
      if (Number(code) !== 200) return;
      messageApi.success(message || t('public.successfulOperation'));
      createFormRef.current?.resetFields();
      goBack(true);
    } finally {
      setLoading(false);
    }
  };

  return (
    <BasicContent isPermission={id ? pagePermission.update : pagePermission.create}>
      { contextHolder }
      <BasicCard>
        <div className='mb-50px'>
          <Spin spinning={isLoading}>
            <BasicForm
              ref={createFormRef}
              list={createList(t)}
              data={createData}
              labelCol={{ span: 5 }}
              handleFinish={handleFinish}
            />
          </Spin>
        </div>
      </BasicCard>

      <SubmitBottom
        isLoading={isLoading}
        goBack={() => goBack()}
        handleSubmit={handleSubmit}
      />
    </BasicContent>
  );
}

export default Page;
